project:
  type: website
  output-dir: docs

website:
  title: "Jenny Shyu's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




