project:
  type: website
  output-dir: docs

website:
  title: "Jenny Shyu's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd
      - href: blog.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


# format:
#   html:
#     theme: [cosmo, custom.scss]
#     css: custom.scss
#     toc: true




